baseurl = "https://prrao87.github.io"
title = "Prashanth Rao"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "The Data Quarry"
  info = "Databases, APIs and everything in between"
  keywords = "blog,data-engineering,python"
  avatarurl = "images/lake-7884049_640.jpg"

  since = 2018

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/prrao87/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/prrao87"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/tech_optimist/"
[[params.social]]
  name = "Medium"
  icon = "fa fa-2x fa-medium"
  weight = 5
  url = "https://medium.com/@tech_optimist"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  url = "https://thedataquarry.com/index.xml"
  rel = "alternate"
  type = "application/rss+xml"


# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"